// ArduinoJson - arduinojson.org
// Copyright Benoit Blanchon 2014-2020
// MIT License

#pragma once

<<<<<<< HEAD
#define ARDUINOJSON_VERSION "6.16.1"
#define ARDUINOJSON_VERSION_MAJOR 6
#define ARDUINOJSON_VERSION_MINOR 16
#define ARDUINOJSON_VERSION_REVISION 1
=======
#define ARDUINOJSON_VERSION "6.15.2"
#define ARDUINOJSON_VERSION_MAJOR 6
#define ARDUINOJSON_VERSION_MINOR 15
#define ARDUINOJSON_VERSION_REVISION 2
>>>>>>> dce77748af3c22e162ad61f1af6ada0e8e718323
